### ISSUE TITLE
Entering e-mail address shows "Internal server error"

### ISSUE THREAD

**Issue by mcrot** [ComputationalMechanics/TopoBank#292]
A colleague just told me, that an error messages shows up when one enters an e-mail address in one's profile.

I think this is related to #130 , but additionally there should be a more friendly message.

**Comment by mcrot** [comment]
It seems like this issue was accidentally closed by a wrong commit message?! Reopening.

**Comment by mcrot** [comment]
This does not happen in my local development instance.

**Comment by mcrot** [comment]
Underlying exception can be reproduced like this:
```
$ docker-compose -f production.yml run --rm django python manage.py shell 
Starting topobank_postgres_1 ... done
Starting topobank_rabbitmq_1  ... done
Starting topobank_memcached_1 ... done
PostgreSQL is available
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
>>> 
>>> from django.core.mail import send_mail
>>> send_mail(
...     'Subject here',
...     'Here is the message.',
...     'from@example.com',
...     ['to@example.com'],
...     fail_silently=False,
... )
Traceback (most recent call last):
  File "<console>", line 6, in <module>
  File "/opt/conda/lib/python3.7/site-packages/django/core/mail/__init__.py", line 60, in send_mail
    return mail.send()
  File "/opt/conda/lib/python3.7/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/conda/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/opt/conda/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/opt/conda/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/opt/conda/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/opt/conda/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/opt/conda/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/opt/conda/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
>>> 
```

**Comment by mcrot** [comment]
The port is accessible from within the Docker container:
```
>>> from telnetlib import Telnet
>>> with Telnet('mail.uni-freiburg.de', 465) as tn:
...     tn.interact()
... 
HELO
F*** Connection closed by remote host ***
>>> 
```
So maybe it's a config issue.

**Comment by mcrot** [comment]
There is simply an important command missing which transfers the EMAIL_CONFIG contents
to the regular variables:
```
vars().update(EMAIL_CONFIG)
```

Then it works on the console. I'll apply this fix and close this. Reopen, if this happens again.

**Comment by mcrot** [comment]
This is probably also the root cause for #130, I'll close that too with this fix.
